name: Deploy to DegitalOcean

on:
  push: 
    branches: ["main"]
  workflow_dispatch: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: '7.0.x'
      
    - name: Build and Publish
      run: |
        dotnet build --configuration Release
        dotnet publish --configuration Release --output ./publish
    - name: Setup Cloudflared
      env:
        HOST: ${{ secrets.IPADDRESS }}
      run: |
        sudo mkdir -p --mode=0755 /usr/share/keyrings
        curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
        echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared buster main' | sudo tee /etc/apt/sources.list.d/cloudflared.list
        sudo apt-get update && sudo apt-get install cloudflared
        mkdir -p "~/.ssh"
        echo -e "Host $HOST\n  ProxyCommand /usr/local/bin/cloudflared access ssh --hostname %h" >> "~/.ssh/config"
        ssh-config-update
    - name: Deploy to DigitalOcean
      env:
        PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        HOST: ${{ secrets.IPADDRESS }}
        USER: ${{ secrets.USER }}
        APP_DIR: /home/${{ secrets.USER }}/Stella-OpenAI
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        rsync -avzr -e 'ssh -o ProxyCommand="/usr/local/bin/cloudflared access ssh --hostname %h" -i private_key.pem -o StrictHostKeyChecking=no' --delete ./publish/ $USER@$HOST:$APP_DIR
        ssh -i private_key.pem -o ProxyCommand="/usr/local/bin/cloudflared access ssh --hostname %h" -o StrictHostKeyChecking=no $USER@$HOST "cd $APP_DIR && sudo systemctl restart stella-openai"
        rm -f private_key.pem
